name: Issue Report (čeština)
description: Něco nefunguje tak, jak by mělo. Pokud to pro vás není problém, preferujte prosím nahlášení v angličtině.
labels: ["triage"]
assignees:
  - jansequens
body:
  - type: markdown
    attributes:
      value: |
        Než nahlásíte nový problém, zkuste se podívat, zda už nebyl nahlášen.
  - type: dropdown
    id: vehicle_model
    attributes:
      label: Model vozu
      description: Vyberte model vašeho vozu.
      multiple: true
      options:
        - Elroq
        - Enyaq
        - Fabia
        - Kamiq
        - Karoq
        - Kodiaq
        - Octavia
        - Scala
        - Superb
        - Jiný model
    validations:
      required: true
  - type: input
    id: vehicle_year
    attributes:
      label: Rok výroby
      description: Zadejte rok výroby vašeho vozu.
      placeholder: "např. 2023"
    validations:
      required: true
  - type: dropdown
    id: vehicle_powertrain
    attributes:
      label: Typ pohonu
      description: Vyberte typ pohonu vašeho vozu.
      options:
        - Spalovací motor (čistě benzín nebo nafta) (ICE)
        - Mild hybrid (MHEV)
        - Plug-in hybrid (PHEV)
        - Full hybrid (HEV)
        - Nějaký druh hybridu — nevím přesně
        - Plně elektrický (BEV)
    validations:
      required: true
  - type: input
    id: vehicle_model_detailed
    attributes:
      label: Model vozu
      description: Pokud váš model není uveden nebo chcete uvést podrobnosti, zadejte je sem.
      placeholder: "např. Octavia Combi RS"
    validations:
      required: false
  - type: input
    id: system_version
    attributes:
      label: Verze systému
      description: Verze systému/software (najdete ji v infotainmentu). Uveďte co nejvíce podrobností.
      placeholder: "např. Hardware: H10, Software: 2630"
    validations:
      required: false
  - type: dropdown
    id: category
    attributes:
      label: Oblast problému
      description: Vyberte hlavní systém, kterého se problém týká..
      options:
        - Asistenční systémy (ACC, Lane Assist, atd.)
        - Konektivita (telefon, CarPlay, Android Auto, Bluetooth)
        - Jiný
    validations:
      required: true
  - type: textarea
    id: behavior-current
    attributes:
      label: Popis problému (aktuální chování)
      description: Popište, co se děje, a uveďte, jakými kroky lze problém vyvolat.
      placeholder: "např. ACC neudržuje rychlost při jízdě do kopce."
    validations:
      required: true
  - type: textarea
    id: behavior-expected
    attributes:
      label: Očekávané chování
      description: Popište, jaké by mělo být správné chování.
      placeholder: "např. ACC by měl udržovat rychlost bez ohledu na stoupání nebo klesání."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Díky, že jste si našli čas udělat Škodovky lepší!
  - type: input
    id: contact
    attributes:
      label: Vaše kontaktní údaje
      description: Volitelné. Jak vás můžeme kontaktovat, pokud budeme potřebovat více informací?
      placeholder: "např. email@example.com"
    validations:
      required: false
