name: Issue Report (v češtině)
description: Něco nefunguje tak, jak by mělo. Pokud to pro vás není problém, preferujte prosím nahlášení v angličtině.
labels: ["triage", "lang: cz"]
assignees:
  - jansequens
body:
  - type: markdown
    attributes:
      value: |
        Než nahlásíte nový problém, zkuste se podívat, zda už nebyl nahlášen.
  - type: dropdown
    id: vehicle_model
    attributes:
      label: Model vozu
      description: Vyberte model vašeho vozu.
      multiple: true
      options:
        - Elroq
        - Enyaq
        - Fabia
        - Kamiq
        - Karoq
        - Kodiaq
        - Octavia
        - Scala
        - Superb
        - Jiný
    validations:
      required: true
  - type: input
    id: vehicle_year
    attributes:
      label: Rok výroby
      description: Zadejte rok výroby vašeho vozu.
      placeholder: "např. 2023"
    validations:
      required: true
  - type: dropdown
    id: vehicle_powertrain
    attributes:
      label: Typ pohonu
      description: Vyberte typ pohonu vašeho vozu.
      options:
        - Spalovací motor (čistě benzín nebo nafta) (ICE)
        - Mild hybrid (MHEV)
        - Plug-in hybrid (PHEV)
        - Full hybrid (HEV)
        - Nějaký druh hybridu — nevím přesně
        - Plně elektrický (BEV)
    validations:
      required: true
  - type: input
    id: vehicle_model_detailed
    attributes:
      label: Model vozu
      description: Pokud váš model není uveden nebo chcete uvést podrobnosti, zadejte je sem.
      placeholder: "např. Octavia Combi RS"
    validations:
      required: false
  - type: dropdown
    id: vehicle_infotainment
    attributes:
      label: Model infotainmentu
      description: Vyberte infotainment, kterým je vůz vybaven.
      options:
        - 13" (alias Media 13" / Navi 13"; pro Elroq, Enyaq; s dotykovou lištou)
        - 8" (alias Media 8", pro Fabia, Scala, Kamiq, Karoq)
        - 10" (alias Media 10", pro Kodiaq, Superb, Octavia; může mít Smart Dials)
        - Navigation 9" (alias Navi 9"; pro Fabia, Scala, Kamiq, Karoq)
        - Navigation 13" (alias Navi 13"; pro Kodiaq, Superb, Octavia; má Smart Dials)
        - Swing 6.5" (pro Fabia)
        - Jiný
        - Žádný infotainment
        - Nevím
    validations:
      required: true
  - type: input
    id: system_version
    attributes:
      label: Verze systému
      description: Verze systému/software (najdete ji v infotainmentu). Uveďte co nejvíce podrobností.
      placeholder: "např. Hardware: H10, Software: 2630"
    validations:
      required: false
  - type: input
    id: phone_details
    attributes:
      label: Informace o telefonu
      description: Pokud problém souvisí s telefonem, uveďte jeho model a verzi operačního systému.
      placeholder: "e.g. iPhone 14 Pro, iOS 17."
    validations:
      required: false
  - type: dropdown
    id: category
    attributes:
      label: Oblast problému
      description: Vyberte hlavní systém, kterého se problém týká..
      options:
        - Asistenční systémy (ACC, Lane Assist, atd.)
        - Konektivita (telefon, CarPlay, Android Auto, Bluetooth)
        - Topení a klimatizace
        - Head-up displej (HUD)
        - Jiný
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Not a native speaker? These terms might help:
        - *instrument cluster* – display or gauges behind the steering wheel  
        - *center console* – area between the front seats with controls and storage  
        - *adaptive cruise control (ACC)* – keeps a set distance from the car ahead  
        - *lane keeping assist* – helps keep the car in its lane (aka Lane Assist)  
        - *blind spot monitor* – warns of cars in your blind spots 
        - *forward collision warning (FCW)* – alerts if a crash is likely (aka Front Assist)
        - *automatic emergency braking (AEB)* – brakes automatically to avoid or reduce a crash (part of Front Assist)
        - *steering wheel controls* – buttons on the steering wheel for audio, menus, etc.  
        - *stalks* – levers on either side of the steering wheel for signals, lights, wipers.  
        - *gear selector* – lever or knob to choose drive, reverse, park, etc.  
        - *parking brake* – keeps the car from rolling when parked.
  - type: textarea
    id: behavior-current
    attributes:
      label: Popis problému (aktuální chování)
      description: Popište, co se děje, a uveďte, jakými kroky lze problém vyvolat.
      placeholder: "např. ACC neudržuje rychlost při jízdě do kopce."
    validations:
      required: true
  - type: textarea
    id: behavior-expected
    attributes:
      label: Očekávané chování
      description: Popište, jaké by mělo být správné chování.
      placeholder: "např. ACC by měl udržovat rychlost bez ohledu na stoupání nebo klesání."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Díky, že jste si našli čas udělat Škodovky lepší!
  - type: input
    id: contact
    attributes:
      label: Vaše kontaktní údaje
      description: Volitelné. Jak vás můžeme kontaktovat, pokud budeme potřebovat více informací?
      placeholder: "např. email@example.com"
    validations:
      required: false
