name: Issue Report (English)
description: Something is not working as expected.
labels: ["triage", "lang: en"]
assignees:
  - jansequens
body:
  - type: markdown
    attributes:
      value: |
        Before filing a new bug, please take a moment to do a quick search to see if the bug has already been reported.
  - type: dropdown
    id: vehicle_model
    attributes:
      label: Vehicle Model
      description: Select your vehicle model.
      multiple: true
      options:
        - Elroq
        - Enyaq
        - Fabia
        - Kamiq
        - Karoq
        - Kodiaq
        - Octavia
        - Scala
        - Superb
        - Other
    validations:
      required: true
  - type: input
    id: vehicle_year
    attributes:
      label: Year of Manufacture
      description: Enter the year your vehicle was manufactured.
      placeholder: "e.g. 2023"
    validations:
      required: true
  - type: dropdown
    id: vehicle_powertrain
    attributes:
      label: Powertrain Type
      description: Select your vehicle’s powertrain.
      options:
        - Combustion engine (petrol or diesel only) (ICE)
        - Mild hybrid (MHEV)
        - Plug-in hybrid (PHEV)
        - Full hybrid (HEV)
        - Some kind of hybrid — I'm not sure
        - Fully electric (BEV)
    validations:
      required: true
  - type: input
    id: vehicle_model_detailed
    attributes:
      label: Vehicle Model
      description: If your model isn’t listed or you want to add details, enter them here.
      placeholder: "e.g. Octavia Combi RS"
    validations:
      required: false
  - type: dropdown
    id: vehicle_infotainment
    attributes:
      label: Infotainment Model
      description: Select your vehicle’s infotainment model.
      options:
        - 13" (aka Media 13" / Navi 13"; for Elroq, Enyaq; has a touch-slider)
        - 8" (aka Media 8", for Fabia, Scala, Kamiq, Karoq)
        - 10" (aka Media 10", for Kodiaq, Superb, Octavia; might have smart dials)
        - Navigation 9" (aka Navi 9"; for Fabia, Scala, Kamiq, Karoq)
        - Navigation 13" (aka Navi 13"; for Kodiaq, Superb, Octavia; has smart dials)
        - Swing 6.5" (for Fabia)
        - Other
        - No infotainment system
        - I'm not sure
    validations:
      required: true
  - type: input
    id: system_version
    attributes:
      label: System Version
      description: Version of the affected system/software (found in infotainment system info). Include as much detail as possible.
      placeholder: "e.g. Hardware: H10, Software: 2630"
    validations:
      required: false
  - type: input
    id: phone_details
    attributes:
      label: Phone Details
      description: If the issue is related to phone connectivity, provide your phone model and OS version.
      placeholder: "e.g. iPhone 14 Pro, iOS 17."
    validations:
      required: false
  - type: dropdown
    id: category
    attributes:
      label: Affected System
      description: Select the primary system affected (best guess).
      options:
        - UI/UX (how it looks and how easy it is to use)
        - Driving Assistance (ACC, Lane Assist, etc.)
        - Connectivity (phone, CarPlay, Android Auto, Bluetooth)
        - Climate control (AC, heating, ventilation)
        - Head-up Display (HUD)
        - Other
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Not a native speaker? These terms might help:
        - *instrument cluster* – display or gauges behind the steering wheel  
        - *center console* – area between the front seats with controls and storage  
        - *adaptive cruise control (ACC)* – keeps a set distance from the car ahead  
        - *lane keeping assist* – helps keep the car in its lane (aka Lane Assist)  
        - *blind spot monitor* – warns of cars in your blind spots 
        - *forward collision warning (FCW)* – alerts if a crash is likely (aka Front Assist)
        - *automatic emergency braking (AEB)* – brakes automatically to avoid or reduce a crash (part of Front Assist)
        - *steering wheel controls* – buttons on the steering wheel for audio, menus, etc.  
        - *stalks* – levers on either side of the steering wheel for signals, lights, wipers.  
        - *gear selector* – lever or knob to choose drive, reverse, park, etc.  
        - *parking brake* – keeps the car from rolling when parked.
  - type: textarea
    id: behavior-current
    attributes:
      label: Issue Description (Current Behavior)
      description: Describe what’s happening now, with steps to reproduce.
      placeholder: "e.g. The ACC does not maintain speed when going uphill."
    validations:
      required: true
  - type: textarea
    id: behavior-expected
    attributes:
      label: Expected Behavior
      description: Describe what should happen instead.
      placeholder: "e.g. The ACC should maintain speed regardless of the incline."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make Škoda vehicles better!
  - type: input
    id: contact
    attributes:
      label: Your Contact Details
      description: Optional. How can we reach you if we need more info?
      placeholder: "ex. email@example.com"
    validations:
      required: false
